name: Ruby

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Run tests that should pass
      run: |
        export WEB_DRIVER=chrome
        export BS_CONFIG=win10_edge
        gem install bundler
        bundle install
        chmod +x run_tests.sh
        ./run_tests.sh --tags @pass
