name: Ruby

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.6.5
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.5
    - name: Run tests that should pass
      run: |
        ruby -v
        gem install bundler
        bundle install
        chmod +x run_tests.sh
        ./run_tests.sh --tags @pass
